version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - database
  gateway:
    image: service-gateway
    container_name: service-gateway
    ports:
      - 80:8080
  user:
    restart: always
    image: service-user
    container_name: service-user
    ports:
      - 8081:8080
    networks:
      - database
networks:
  database:
    external: false